name: up_home
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.2
  intl: ^0.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - asset/icon/login_logo.png
   - asset/icon/notice.png
   - asset/icon/aides.png
   - asset/icon/task.png
   - asset/icon/order.png
   - asset/icon/history.png
   - asset/icon/order_detail.png
   - asset/icon/product_detail.png
   - asset/icon/schedule.png
   - asset/icon/exception.png
   - asset/icon/wallet.png
   - asset/icon/university.png
   - asset/icon/arrow_right.png
   - asset/icon/call.png
   - asset/icon/calendar.png
   - asset/image/person.jpg
   - asset/image/banner0.jpg
   - asset/image/banner1.jpg
   - asset/image/banner2.jpg
   - asset/image/picture.png
   - asset/image/customer_avatar.png
   - asset/image/location.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
